---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
      solveButton: false
    - name: "02-image-mode"
      label: "Image Mode"
      solveButton: false
    - name: "03-configure-ansible"
      label: "Configure Ansible"
      solveButton: false
    - name: "04-rex-pull-mode"
      label: "Rex Pull Mode"
      solveButton: false
    - name: "05-custom-repo"
      label: "Custom Repo"
      solveButton: false
    - name: "06-iss-export"
      label: "Iss Export"
      solveButton: false
    - name: "07-iss-network"
      label: "Iss Network"
      solveButton: false
    - name: "08-conclusion"
      label: "Conclusion"
      solveButton: false

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
  - name: "satellite.lab terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel1.lab terminal"
    url: /wetty_rhel1/ssh/root
  - name: "rhel2.lab terminal"
    url: /wetty_rhel2/ssh/root
  - name: "Satellite 2 Web UI"
    url: https://satellite-2-${guid}.${domain}/
  - name: "satellite-2.lab terminal"
    url: /wetty_satellite-2/ssh/root
