---
virtualmachines:
  - name: "satellite"
    image: "satellite-server-rhdp-1-6-17-07-02-25"
    bootloader: efi
    register_satellite: false
    memory: "32G"
    cores: 8
    image_size: "540G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    userdata: |
      #cloud-config
      fqdn: satellite.lab
      hostname: satellite
      prefer_fqdn_over_hostname: true
      manage_etc_hosts: true
    services:
      - name: satellite-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: satellite-https
    routes:
      - name: satellite-https
        host: satellite
        service: satellite-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIGyTCCBLGgAwIBAgIUZPQwm28Gh5V2T/aZvVelkHZYRB4wDQYJKoZIhvcNAQEL
          BQAweDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
          VQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdLYXRlbGxvMRQwEgYDVQQLDAtTb21lT3Jn
          VW5pdDEWMBQGA1UEAwwNc2F0ZWxsaXRlLmxhYjAeFw0yNTA2MTMxNjQ3MDZaFw0z
          ODAxMTcxNjQ3MDZaMHgxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJv
          bGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHS2F0ZWxsbzEUMBIGA1UE
          CwwLU29tZU9yZ1VuaXQxFjAUBgNVBAMMDXNhdGVsbGl0ZS5sYWIwggIiMA0GCSqG
          SIb3DQEBAQUAA4ICDwAwggIKAoICAQC5avfCtHGpQ8u8NG51KImH4nAVmamnk7XV
          GnNcd4TUImBmZHKpApTg/0U3yzi7IOPTMJr20a2J8aV7ln2dFm09C6RCmX/j6DaZ
          9nYGpQiJ71mVWyf5U3ZWRoTZB80E3n+vBWQZywTgGk59cBTbAIdu2K+XUql16exa
          psiB3m0glbZk5ZQSjJxvOiwbQhuThk+ZJCnD8xhJJf9ZOlw8KHob1aN7SKCP7NQS
          H/FTmB3c4ZixnvjPiDSNMjFyViMgMTGQLAK9Rn9V0a7tMIGttCeSh5WmXgWT9k7N
          sWIR0Q4kJBSevyFhFKKfeO1v3V+B3Z/0VDwKWd46Q8deWSEWIsMKrw2Ix89Q/ba9
          ZkWF3RSYwfQ2MjuYsFhcCytCs05eviK9ROG+PFye6dQGzZKVGrs6+OkAM+awiioo
          n+O/dLFArt5c6q7puemfxcC0Q9DSaR/n3WwZKHqI3mYCzu5CzVyXPpUa/pKFCJt/
          AGY++KhgM8+KYVqzf0+nNssRDpkp8/hiPV9uMFcW+RBHjAuIgAk/JXlXudaHci/g
          gNPkSHAKiUvxi/bKgGMYBfGyCQ7i+De4BZxTFuPXF8pAoCjKstiVqXdntib5S2EY
          dvU0XPBeg+oVIHrsZfyct5yyDjwxV5iF0pmK1GlYI8Kn1cgO10ODx/PeoDqfZkAl
          ZYBI3u5lnQIDAQABo4IBSTCCAUUwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMCAaYw
          HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBEGCWCGSAGG+EIBAQQEAwIC
          RDA1BglghkgBhvhCAQ0EKBYmS2F0ZWxsbyBTU0wgVG9vbCBHZW5lcmF0ZWQgQ2Vy
          dGlmaWNhdGUwHQYDVR0OBBYEFOjBiNX5PCHp5w7n9wd/6u3/jJhuMIGfBgNVHSME
          gZcwgZShfKR6MHgxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGlu
          YTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHS2F0ZWxsbzEUMBIGA1UECwwL
          U29tZU9yZ1VuaXQxFjAUBgNVBAMMDXNhdGVsbGl0ZS5sYWKCFGT0MJtvBoeVdk/2
          mb1XpZB2WEQeMA0GCSqGSIb3DQEBCwUAA4ICAQA2pxqcZzAOD2nvx3O8ZVuvbasb
          0bZzFF2zrjTVaUFkDwkhAXL5PCfcs/740OCsrFPSrzE5r7VIvb06t7X3mfn0Iw9N
          1h9jkQMk4sjNGzG3F0Q24uPDmuPZiuaqBTB1uvCnGjYpQH29yDKx0OFWLqhfYLHt
          c0Z9aTrHKBzchJtwvf/9GWkCYxq8voH4IQ/VcfwO2iINQtSzgmxcpDoNC1J0AUCx
          yMBnCNxrVJ/28fKafgi6rblPPaFoTSIff+nuTtmUSfKuL+gfkSV/QvReWXErCJCa
          mWaf0sIQhEbQvDjvF/8kUURtf1HK/iittGTlaBYjkjN4J7Pnr81YwQZ2mu0ESdrS
          lcXxr7tnsOB+/yGz7qGVPaVQNi61zDUtIJQ9j8GV3Fwr2aetH36aXn/MxXoWccKk
          WufJrhWHldfPRU48xBih8aUHlohfGHsf6jl0bHEq8LOOJDujr1A5po9iFWf92wbn
          x2N31X0P8IiXwHG5SWjPio5gzoQkLLT4getxNETVRMTgJNXpU4Hn14oOZIqEDxaR
          zMLexMYBTiQO6mtvZo7aTL3x8hRoReJvjp0TmRBoPeyEU8lx19dE8ujVBVqq8R5a
          T80+iomU6lMVM7belMf0tl0loa/D+vjd0jfGnip+4ewbEr+dj9TAzfsCBidLrl4a
          +WTV/ogDLLZX8gj6kg==
          -----END CERTIFICATE-----
  - name: "satellite-2"
    image: "satellite-server-rhdp-2-6-17-07-08-25"
    bootloader: efi
    register_satellite: false
    memory: "32G"
    cores: 8
    image_size: "540G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
    userdata: |
      #cloud-config
      fqdn: satellite-2.lab
      hostname: satellite-2
      prefer_fqdn_over_hostname: true
      manage_etc_hosts: true
    services:
      - name: satellite-2-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: satellite-2-https
    routes:
      - name: satellite-2-https
        host: satellite-2
        service: satellite-2-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIGzzCCBLegAwIBAgIUGCAmYlXbEGLQ4GR3FJGg3iYAC3IwDQYJKoZIhvcNAQEL
          BQAwejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
          VQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdLYXRlbGxvMRQwEgYDVQQLDAtTb21lT3Jn
          VW5pdDEYMBYGA1UEAwwPc2F0ZWxsaXRlLTIubGFiMB4XDTI1MDYyMzE3NDk1MVoX
          DTM4MDExNzE3NDk1MVowejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENh
          cm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdLYXRlbGxvMRQwEgYD
          VQQLDAtTb21lT3JnVW5pdDEYMBYGA1UEAwwPc2F0ZWxsaXRlLTIubGFiMIICIjAN
          BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuJWKV6yMdF3rT5O7gVrKv8NOgXe2
          5sTz4a+imjeotaq6r6RLnAz666yDnF2zbvl6TlOH1XDxiumMymHfkpNeOo99RWmK
          j2YROPiRQyfk80m52IKakEv+fg6WQaanseBBQ8mqYd3IH1yDBAd9bVgAKcpi4Jgc
          UuUmkgpQTAsJzUK7zRIQj9wTSExBBbPgRIk/7S8HS5Nv3S8grl6xW5dTq81N+l/j
          TCzkNM+F4eGJrJqZsrJEZEC7YAZo0KR1c0cdb/WNEhcLFNNcXB158UbqHgWCFUEp
          Dw1lF/+rN5+TUn61Lx0wKOEfm7Z2pYd2nNHxrF/iP0+8meGliAminjiJmGgNpy3h
          ZlqO2SNlMSaGsAZ1kC2jCzFK658ToZ022Yo9rWzOfSE+y+Q84Y4Q6J033aA+9Ka8
          yNx0EJpv0rE7p61ZDxU6HAZwXX2tc91NmO14IXryy49ygHQ/jaVk/FKRW2u7BklA
          FgeMsa204uRg6irPPJEV+cjNUYDB0vH/Qf3/nFEZJ5Uk9Yu0/b3JgziZyDO9dEGA
          ua6Fk2byI6VzGknNJknbo3zyFH8zatlECDW+c8GOk7lw+GqHU+MIIJIP6m36kU3v
          ggveExy0tqw0xnugniijP4MNV4YEEQChqCpeL9kfC692UFLTPqIu6CcnD1ha5XGQ
          hHKIQyqrTHhNyH0CAwEAAaOCAUswggFHMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQD
          AgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjARBglghkgBhvhCAQEE
          BAMCAkQwNQYJYIZIAYb4QgENBCgWJkthdGVsbG8gU1NMIFRvb2wgR2VuZXJhdGVk
          IENlcnRpZmljYXRlMB0GA1UdDgQWBBToFUHz779FVH7N4Q0qJIUvyM2VDjCBoQYD
          VR0jBIGZMIGWoX6kfDB6MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fy
          b2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxEDAOBgNVBAoMB0thdGVsbG8xFDASBgNV
          BAsMC1NvbWVPcmdVbml0MRgwFgYDVQQDDA9zYXRlbGxpdGUtMi5sYWKCFBggJmJV
          2xBi0OBkdxSRoN4mAAtyMA0GCSqGSIb3DQEBCwUAA4ICAQB8P9YXlT9I4binxMZL
          7CFfzxnJebAvqnneb83s0KylO9fjC1sLsWxv34DpADcCbAq6OaTEa5/vKV8SHAmK
          Kz+ibvckqqeYolF/p68jxrqe0M8bucLua7l4XWVjJQ7Io5HIQ5dV9aeTcjYkCa49
          O7i/i2Uish4cnw5KyqZkOB/vjvcu6nfXttKYxETY+MqTypy4bvyu51LcSdksESb2
          j9kH5vZLl6UDShItl+TbC5HS92IlwMKnbwQ74W2s9U3y1nCBN33k0LRk7b6NKaIu
          xGeWPFljpvDZio8jwh12HO2vxaTg12daQnT5KhumqaBB4nNb2Ee/AOfN++rdaxRX
          vrxjK0nG62aA2cl2V1Gu5xEUbZIVWH+RP3ZVy1/OCCknWE3dpY5WzUNs9CTu5hT5
          4tN2eoeaUapOsbDyMsGm/x8nsK/lSq86gKi/ttglvgxufpaZEnV8HXu3aLQSjUpr
          bkcFAAZ7kS8qZ0LPf2IhyYMQ+H8Irvq2XyvA+nDVYioBS964g2wwzKB3fAAcKjaa
          HxzNmGvBwi4DpKG4Y8LR/a2sJoI2HQGgTqHDjAxI3CHqOw1tPtQIkAFWAmtwcKgc
          v6KKlJA1eJb5pJEUS26kgyamjV92BWrTTbqebrd/35ZJhZdZ4EEMsfb8oMJXDeps
          pLDuXqwuPfSvhVIzwLgvnYlTlQ==
          -----END CERTIFICATE-----
  - name: "rhel1"
    image: "rhel-10-0-07-09-25-2"
    bootloader: efi
    register_satellite: false
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
    userdata: |
      #cloud-config
      fqdn: rhel1.lab
      hostname: rhel1
      prefer_fqdn_over_hostname: true
      manage_etc_hosts: true
  - name: "rhel2"
    image: "rhel-10-0-07-09-25-2"
    bootloader: efi
    register_satellite: false
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
    userdata: |
      #cloud-config
      fqdn: rhel2.lab
      hostname: rhel2
      prefer_fqdn_over_hostname: true
      manage_etc_hosts: true
